[project]
name = "asi"
version = "0.1.0"
description = "Iris classifier API"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.29",

    "pandas>=2.3.3",
    "scikit-learn>=1.6.1",

    "jupyter>=1.1.1",
    "notebook>=7.5.0",
]
